### ISSUE TITLE
Fonts are screwed on Windows

### ISSUE THREAD

**Issue by mikejzx** [MasterQ32/kristall#116]
Environment: Windows 8.1
* It seems like since 808288ce691a3c1520db513c7cff79fd22d3c53f the fonts on Windows are not displaying properly in the text_browser when rendering non-HTML pages. It looks like this is due to the font substitutions not taking effect on the `Kristall XX` fonts (Qt bug maybe?). As a result, Qt selects an ugly default font instead of the one set in preferences.
* Additionally, if you go into the settings and change the theme font, the correct font is used until restarting the program, however this might just be a corner-case bug in 808288ce691a3c1520db513c7cff79fd22d3c53f

Commenting out [this line](https://github.com/MasterQ32/kristall/commit/808288ce691a3c1520db513c7cff79fd22d3c53f#diff-9ef52b126a746824845a17e3e84f3d30c3fc37f3cfacbe792d9acb9a687fbf09R360) resolves the issue, but of course this removes the emoji workaround, so we'd have to find some other way to fix this (maybe we can try not using `Kristall XX` fonts on Windows and hope that UI still renders properly)

**Comment by krkk** [comment]
I've got similar bug, but for me it looks like the fonts are broken only when there is a foundry in the font family name.

My workaround would be to call `QFont::setFamilies`instead of creating substitutions and to do a nasty ifdef check, because that's a Qt5.13+ feature. Unfortunately, that mean users using an older Qt version won't get colored emojis.
(or maybe to just remove the foundry from the family if that's really the case ¯\\_(ツ)_/¯).

**Comment by mikejzx** [comment]
@krkk 
Try building from [this branch](https://github.com/mikejzx/kristall/tree/emoji_fix) (or master if #173 gets merged), and let me know if it fixes the issue that you're having with the foundries. The patch uses `QFont::setFamilies` like you mentioned 😉

**Comment by krkk** [comment]
@mikejzx Built from master and the problem no longer exists, thanks. :)
