### ISSUE TITLE
gopher renderer double-spaces type 0 files

### ISSUE THREAD

**Issue by cpjhenry** [MasterQ32/kristall#179]
Ex. gopher://zaibatsu.circumlunar.space:70/0/~cpj/phlog/20210214.txt

Type 1 (gophermap) render spaces properly. Type 0 (text), however, shows up as double-spaced. I suspect this is because gopher traditionally expects hard LF at the end of every line (which is usually maxed at 77 characters) -- there's no soft wrapping. Kristall appears to be assuming every hardline is a new paragraph and inserts a blank line. This is not needed with type 0 files.

**Comment by MasterQ32** [comment]
I suspect that this happens because the file has CR LF terminators which might not be handled correctly right now.

This should also affect all `text/plain` files then as gopher type 0 is rendered as such

**Comment by mikejzx** [comment]
The issue seems to be due to the `renderhelpers::renderEscapeCodes` function - since it inserts characters one-at-a-time, the CR and LF characters get inserted seperately by the cursor and oddly appear as two line feeds.

I guess we could fix this by just not rendering carriage-returns at all in that method. Is there actually any use for them to be in plain text files?

**Comment by MasterQ32** [comment]
> I guess we could fix this by just not rendering carriage-returns at all in that method. Is there actually any use for them to be in plain text files?

We can just make a function that will canonicalize the line endings from a input file by *first* replacing `CR` `LF` with `LF`, then replacing `CR` with `LF` yielding a file that has only `LF` terminators.

A lone `CR` was used on MacOS for line termination a long time, but in raw text files it usually has effect and does not appear in the wild very often
