### ISSUE TITLE
Protocol Violation error on conforming server response

### ISSUE THREAD

**Issue by janicetr** [MasterQ32/kristall#43]
Hey! On a non existent resource request, my Gemini server responds with the following:

51 \r\l

The Gemini protocol states, that 

`<STATUS><SPACE><META><CR><LF>`

Status codes beginning with 5 are PERMANENT FAILURE status codes, meaning:

"The request has failed. There is no response body. The nature of the failure is permanent, i.e. identical future requests will reliably fail for the same reason. The contents of META **may** provide additional information on the failure, and should be displayed to human users. Automatic clients such as aggregators or indexing crawlers should not repeat this request."

As of my understanding, the META may be empty, so "51 \r\l" is a valid response.
But Kristall shows the following error message:

Protocol Violation
The server did not serve the content you requested in a well-defined manner and Kristall could not process the data sent.
Line is too short for valid protocol

**Comment by MasterQ32** [comment]
> Line is too short for valid protocol

This means the server closed the connection before Kristall was able to read all data from the connection. I should add a `readAll()` in the close callback to prevent that kind of error, i noticed that some other servers appear to do this too....

Thanks for the report!

**Comment by MasterQ32** [comment]
Hey, do you have me a test case of your server so i can locally reproduce the problem?

**Comment by nico202** [comment]
I could reproduce it.

First, you append 4 chars to the buffer
https://github.com/MasterQ32/kristall/blob/d3931529ccca3edcdb3fa9f0322a8c4352f2f476/src/protocols/geminiclient.cpp#L155
(i is the index, QBuffer append takes a length).

So, the line is now "50<SPACE><CR>", long 4.

Then, we check that the length is at least 5

https://github.com/MasterQ32/kristall/blob/d3931529ccca3edcdb3fa9f0322a8c4352f2f476/src/protocols/geminiclient.cpp#L159

That's why this line:
https://github.com/MasterQ32/kristall/blob/d3931529ccca3edcdb3fa9f0322a8c4352f2f476/src/protocols/geminiclient.cpp#L170
does work (last char in buffer is '\r').

So I'd say it's enough to replace <= 5 with < 4
(The same error happens with "50 a\r\n")

**Comment by nico202** [comment]
However, I don't know the software enough to know if this is going to beak anything else (also, is meta _required_ somewhere? is this already managed elsewhere in the code?)

**Comment by MasterQ32** [comment]
To my understanding, `<META>` should be non-empty in any case, but it *may* not contain useful information. We should ask solderpunk about this, but the fix could be that the `<= 5` is replaced with `< 5`.

**Comment by MasterQ32** [comment]
Thank you github. I tried to fix the issue, @janicetr and @Kevin-Sangeelee, can you confirm that your issues are resolved?

**Comment by nico202** [comment]
As it seems from the mail exchange with solderpunk, the empty meta won't be allowed anymore (but I don't how long will it take to get to a decision)

**Comment by MasterQ32** [comment]
Tested it, empty response now also works
